# SPDX-FileCopyrightText: Copyright 2026 Daniel Balparda <balparda@github.com>
# SPDX-License-Identifier: Apache-2.0
"""TransNext core database module."""

from __future__ import annotations

import abc as abstract
import copy
import enum
import logging
import pathlib
import re
import threading
from collections import abc
from typing import Protocol, Self, TypedDict, cast, runtime_checkable

import tqdm
from PIL import Image
from transcrypto.core import aes, hashes, key
from transcrypto.utils import base as tbase
from transcrypto.utils import config as app_config
from transcrypto.utils import timer

from transnext import __version__
from transnext.core import base

_DB_COMPRESS_LEVEL = 5  # default compression level for DB saving
_DB_DISK_LOCK: threading.Lock = threading.Lock()  # lock for thread-safe DB operations

_EXTENSIONS_TO_PARSE_LOWER: set[str] = {'.png', '.jpg', '.jpeg', '.gif'}


class Error(base.Error):
  """TransNext DB exception."""


class _DBType(TypedDict):
  """DB object type.

  Should be suitable for JSON and pickle serialization, so no complex types or custom classes.
  Don't use sets. Tuples are also bad, they get converted to lists, then comparison fails.
  """

  version: int  # DB version; increment on save
  db_version: str  # package version (transnext.__version__) at time of last save
  last_save: int  # timestamp of last save
  images: dict[str, DBImageType]  # {image_hash: image_metadata}
  models: dict[str, AIModelType]  # {model_hash: model}
  lora: dict[str, AIModelType]  # {model_hash: lora/lycoris}
  known_image_sources: list[str]  # places to track images from
  image_output_dir: str | None  # current directory to save generated images to
  experiments: dict[str, tbase.JSONDict]  # {experiment_hash: newton.ExperimentType}


def _DBTypeFactory(overrides: dict[str, object] | None = None) -> _DBType:
  """Create new _DBType object with default values.

  Returns:
    A new _DBType object with default values.

  """
  obj: _DBType = {
    'version': 0,
    'db_version': __version__,  # set to current package version on creation
    'last_save': timer.Now(),
    'images': {},
    'models': {},
    'lora': {},
    'known_image_sources': [],
    'image_output_dir': None,
    'experiments': {},
  }
  obj.update(overrides or {})  # type: ignore[typeddict-item]
  return obj


class ImageOrigin(enum.Enum):
  """Image origin enum."""

  A1111 = 'A1111'  # generated by Automatic1111, could be from other sources
  SDNext = 'SDNext'  # generated by SDNext, could be from other sources
  TransNext = 'TransNext'  # generated by this software, via SDNext API
  AIUnknown = 'AIUnknown'  # we could parse the metadata, but could not specify the origin


class DBImageType(TypedDict):
  """DB image metadata type.

  We have to consider here duplicates: since the hash is the same we can assume many fields are
  the same, but some will need to be per-file, thus `paths`.
  """

  hash: str  # image hash: the hash of the file on disk, usually a PNG file
  raw_hash: str  # raw image hash: the hash of the raw image data computed internally to PIL
  size: int  # image file size
  width: int  # image width
  height: int  # image height
  format: str  # ImageFormat string (e.g., JPEG, PNG, GIF)
  info: str | None  # original info string from the image metadata; None: could not extract info
  paths: dict[str, DBImagePathType]  # paths where the image is found, keyed by path (duplicates)


class DBImagePathType(TypedDict):
  """DB image on disk metadata type.

  This data varies among duplicates because they might have been generated from different places,
  and might differ in metadata. We can only hope that `ai_meta` will be very similar if we could
  parse it, but even here there is no guarantee...
  """

  main: bool  # is this the main path?
  created_at: int  # timestamp of when the image was added to the DB
  origin: str | None  # ImageOrigin of the image, if known, otherwise None
  parse_errors: dict[str, None] | None  # any errors encountered during parsing of image metadata
  version: str | None  # version of the software that generated the image, if known, otherwise None
  ai_meta: AIMetaType | None  # AI generation metadata; None: not an AI-gen image we could parse
  sd_info: tbase.JSONDict | None  # additional SDNext info API response when WE generated only!
  sd_params: tbase.JSONDict | None  # additional SDNext params API response when WE generated only!


class ModelType(enum.Enum):
  """AI model type enum."""

  safetensors = 'safetensors'
  checkpoint = 'ckpt'
  pt = 'pt'


class ModelFunction(enum.Enum):
  """AI model function enum."""

  Model = 'Model'
  Lora = 'Lora'
  Lycoris = 'Lycoris'


class AIModelType(TypedDict):
  """AI model metadata type.

  Keep it shallow and simple, only primitive types, no complex objects or custom classes,
  to ensure it is comparable and serializable without issues. Avoid lists. No sets and enums.

  Tuples are also bad, they get converted to lists, then comparison fails.
  """

  hash: str  # hash of the model/lora/lycoris file
  name: str  # AI model identifier
  alias: str  # AI model alias; can be equal to name
  autov3: str | None  # AutoV3 hash for LoRAs, or None if not a LoRA
  path: str  # path to the model file
  model_type: str  # ModelType file type (e.g., 'safetensors', 'ckpt')
  function: str  # ModelFunction (e.g., 'Model', 'Lora', 'Lycoris')
  metadata: tbase.JSONDict  # additional metadata from SDNext API response
  description: str | None  # brief description of the model's capabilities


class AIMetaType(TypedDict):
  """AI image metadata.

  This is supposed to hold all the options this software handles that affects image generation,
  so that we can later on use it for filtering and searching images by these parameters.
  It should be complete enough to allow us to reproduce the generation of the image.

  Keep it shallow and simple, only primitive types, no complex objects or custom classes,
  to ensure it is comparable and serializable without issues. Avoid lists. No sets and enums.

  Tuples are also bad, they get converted to lists, then comparison fails.

  ATTENTION: Since this is not so shallow anymore, it needs copy.deepcopy()!
  """

  model_hash: str | None  # AI model hash (only None if we could not parse/find the model)
  positive: str  # positive prompt used for AI processing
  negative: str | None  # negative prompt used for AI processing
  seed: int  # seed used in AI processing
  v_seed: AIMetaVariationSeedType | None  # variation seed or None if not used
  width: int  # image width
  height: int  # image height
  steps: int  # number of steps used in AI processing
  cfg_scale: int  # CFG scale used in AI processing (guidance scale, times 10 for int storage)
  cfg_end: int  # CFG end step used in AI processing (times 10 for int storage)
  cfg_rescale: int  # CFG rescale used in AI processing (times 100 for int storage)
  sampler: str  # base.Sampler string used in AI processing
  parser: str  # base.QueryParser string used for the prompts
  clip_skip: int  # CLIP skip used in AI processing (times 10 for int storage)
  sch_sigma: str | None  # base.SchedulerSigma string used; None is 'default'
  sch_spacing: str | None  # base.SchedulerSpacing string used; None is 'default'
  sch_beta: str | None  # base.SchedulerBeta string used; None is 'default'
  sch_type: str | None  # base.SchedulerPredictionType string used; None is 'default'
  ngms: int | None  # A1111 only/obsolete: “Negative Guidance minimum sigma” (times 100 int storage)
  cfg_skip: int | None  # A1111 only/obsolete: “Skip Early CFG” (times 100 int storage)
  lora: dict[str, str] | None  # {hash: lora_weights_string}; empty dict if no lora/lycoris used
  img2img: AIImg2ImgType | None  # img2img-specific metadata; None if txt2img
  freeu: AIMetaFreeUType | None  # FreeU backbone/skip feature scaling (times 100 int storage)


class AIMetaVariationSeedType(TypedDict):
  """AI image variation seed metadata.

  Keep it shallow and simple, only primitive types, no complex objects or custom classes,
  to ensure it is comparable and serializable without issues. Avoid lists. No sets and enums.

  Tuples are also bad, they get converted to lists, then comparison fails.
  """

  seed: int  # variation seed used in AI processing
  percent: int  # variation strength percent (times 100 for int storage)


class AIMetaFreeUType(TypedDict):
  """AI image FreeU metadata.

  Keep it shallow and simple, only primitive types, no complex objects or custom classes,
  to ensure it is comparable and serializable without issues. Avoid lists. No sets and enums.

  Tuples are also bad, they get converted to lists, then comparison fails.
  """

  b1: int  # backbone 1 scaling (times 100 for int storage)
  b2: int  # backbone 2 scaling (times 100 for int storage)
  s1: int  # skip 1 scaling (times 100 for int storage)
  s2: int  # skip 2 scaling (times 100 for int storage)


def AIMetaTypeFactory(overrides: dict[str, object] | None = None) -> AIMetaType:
  """Create new AIMetaType object with default values.

  SPECIAL CASE: seed in {None, -1, 0} will NOT overwrite, will generate a random seed!
  SPECIAL CASE: v_seed in {None, -1, 0} and strength>0 will NOT overwrite, will generate random seed

  Args:
    overrides: dict of fields to override from the defaults; if None, will use all defaults

  Returns:
    A new AIMetaType object with default values.

  Raises:
    Error: if the resulting seed/v_seed value is invalid (not in the range 0 < s ≤ base.SD_MAX_SEED)

  """
  obj: AIMetaType = AIMetaType(
    model_hash=None,
    positive='',
    negative=None,
    seed=-1,  # start with random flag
    v_seed=None,
    width=base.SD_DEFAULT_WIDTH,
    height=base.SD_DEFAULT_HEIGHT,
    steps=base.SD_DEFAULT_ITERATIONS,
    sampler=base.SD_DEFAULT_SAMPLER.value,
    parser=base.SD_DEFAULT_QUERY_PARSER.value,
    cfg_scale=base.SD_DEFAULT_CFG_SCALE,
    cfg_end=base.SD_DEFAULT_CFG_END,
    cfg_rescale=base.SD_DEFAULT_CFG_RESCALE,
    clip_skip=base.SD_DEFAULT_CLIP_SKIP,
    sch_sigma=None,
    sch_spacing=None,
    sch_beta=None,
    sch_type=None,
    ngms=None,
    cfg_skip=None,
    lora={},
    img2img=None,
    freeu=AIMetaFreeUType(
      b1=base.SD_DEFAULT_FREEU_B1,
      b2=base.SD_DEFAULT_FREEU_B2,
      s1=base.SD_DEFAULT_FREEU_S1,
      s2=base.SD_DEFAULT_FREEU_S2,
    )
    if base.SD_DEFAULT_FREEU
    else None,
  )
  obj.update(overrides or {})  # type: ignore[typeddict-item]
  # make sure seed is actually set now
  obj['seed'] = base.SeedGen() if obj['seed'] in {None, -1, 0} else obj['seed']
  if not 0 < obj['seed'] <= base.SD_MAX_SEED:
    raise Error(f'Invalid `seed` value in AIMetaType: {obj}')
  if (
    obj['v_seed'] is not None
    and obj['v_seed']['seed'] in {None, -1, 0}
    and obj['v_seed']['percent'] > 0
  ):
    obj['v_seed']['seed'] = base.SeedGen()
  if obj['v_seed'] is not None and not 0 < obj['v_seed']['seed'] <= base.SD_MAX_SEED:
    raise Error(f'Invalid `v_seed` value in AIMetaType: {obj}')
  # done
  return obj


class AIImg2ImgType(TypedDict):
  """AI img2img-specific metadata.

  Keep it shallow and simple, only primitive types, no complex objects or custom classes,
  to ensure it is comparable and serializable without issues. Avoid lists. No sets and enums.
  """

  input_hash: str | None  # hash of the initial image used for img2img, if known
  denoising: int  # img2img denoising strength (times 100 for int storage)


class AIDatabase:
  """AI database."""

  def __init__(
    self,
    config: app_config.AppConfig,
    *,
    read_only: bool = False,
    aes_key: aes.AESKey | None = None,
    safe_save: bool = True,
    compress_save: bool = False,
    api: APIProtocol | None = None,
  ) -> None:
    """Initialize the AI Database.

    Args:
      config: The application configuration object.
      read_only: (default False) Whether to open the database in read-only mode.
      aes_key: (default None) Optional AES key for encrypting/decrypting the database file
      safe_save: (default True) Whether to use a safe save method that reads the existing DB file
          before writing, to prevent data loss from clobbering; if False, it will overwrite
          the file directly
      compress_save: (default False) Whether to compress the DB file when saving; if True, it will
          save as a compressed file
      api: (default None) APIProtocol instance to use for fetching available models automatically

    """
    self._config: app_config.AppConfig = config
    self._read_only: bool = read_only
    self._key: aes.AESKey | None = aes_key
    self._safe_save: bool = safe_save
    self._compress_save: bool = compress_save
    self._db: _DBType
    self._open = timer.Timer('AIDatabase', emit_log=False)
    with _DB_DISK_LOCK:  # ensure thread-safe load operations
      if self._config.path.exists():
        self._db = cast(
          '_DBType', config.DeSerialize(decryption_key=self._key, unpickler=key.UnpickleJSON)
        )
        logging.info(f'Loaded DB from {self._config.path}: {self.label}')
      else:
        self._db = _DBTypeFactory()
        logging.warning(f'DB file not found, will start fresh, {self.label}')
    if self._read_only:
      logging.warning('ATTENTION: AIDatabase opened in read-only mode, changes will not be saved!')
    # compute indexes on the fly
    self._raws: dict[str, set[str]] = {}
    self._paths: dict[str, str] = {}
    self._ComputeIndexes()
    # if API provided, refresh models/lora from API and save to DB
    if api:
      logging.info('API provided: refreshing DB models/lora')
      orig_n: int = len(self._db['models'])
      self.RefreshDBModels(api)
      if len(self._db['models']) > orig_n:
        self.Save()  # save if we added new models from API (reason: hashing is costly)
      orig_n = len(self._db['lora'])
      self.RefreshDBLora(api)
      if len(self._db['lora']) > orig_n:
        self.Save()  # save if we added new lora/lycoris from API (reason: hashing is costly)

  def _ComputeIndexes(self) -> None:  # noqa: C901
    """Compute indexes for quick lookups. Check DB consistency.

    Raises:
      Error: if there are inconsistent entries in the DB

    """
    # reset indexes
    self._raws = {}
    self._paths = {}
    with timer.Timer(emit_log=False) as tmr:  # noqa: PLR1702
      # go over images, build indexes
      for h, img in self._db['images'].items():
        # raw hash is just a collection of all the paths that land in the same raw hash
        self._raws.setdefault(img['raw_hash'], set()).add(h)
        # paths we add one by one so we can check all paths are individually unique
        for p, obj in img['paths'].items():
          if p in self._paths:
            raise Error(f'Duplicate path: {p!r} exists in {self._paths[p]!r} & {h!r}: {img}')
          self._paths[p] = h
          if (meta := obj['ai_meta']) is not None:
            if (mh := meta['model_hash']) is not None and mh not in self._db['models']:
              logging.error(f'Image {h!r}/{p} has unknown model hash {mh!r}')
            if meta['lora']:
              for lh in meta['lora']:
                if lh not in self._db['lora']:
                  logging.error(f'Image {h!r}/{p} has unknown lora hash {lh!r}')
      # go over models and lora and check they exist
      for tp, models_dict in (('Model', self._db['models']), ('Lora', self._db['lora'])):
        for mh, model in models_dict.items():
          name: str = model['name']
          if mh != model['hash']:
            raise Error(f'{tp} hash mismatch, {name}: key {mh!r} vs model {model}')
          if not pathlib.Path(model['path']).exists():
            logging.error(f'{tp} {mh!r}, {name} has non-existent path: {model["path"]}')
    # done
    logging.info(
      f'Refreshed indexes in {tmr}: {len(self._db["images"])} img / {len(self._raws)} unique raw '
      f'hashes, {len(self._paths)} unique paths'
    )

  def __enter__(self) -> Self:
    """Context manager entry, returns self.

    Returns:
      self, for use within the context

    """
    return self

  def __exit__(
    self,
    exc_type: type[BaseException] | None,
    _exc_value: BaseException | None,
    _traceback: object,
  ) -> None:
    """Context manager exit. If not exception, saves the database to file.

    Args:
      exc_type: exception type, if any
      _exc_value: exception value, if any
      _traceback: traceback object, if any

    """
    logging.info(f'AIDatabase was open for {self._open}')
    if exc_type is not None:
      logging.error('Exception occurred in AIDatabase context: *NOT* saving DB due to exception')
      return  # do not save if there was an exception
    self.Save()

  @property
  def label(self) -> str:
    """Get a human-readable label for the database, for logging and display purposes.

    Returns:
      string '#<N>@<tm>'

    """
    return _DBLabel(self._db)

  @property
  def experiments(self) -> dict[str, tbase.JSONDict]:
    """Get the experiments stored in the database. MUTABLE!! If you alter you alter the DB.

    Returns:
      Dictionary of experiments, keyed by experiment hash.

    """
    return self._db['experiments']

  def Raw(self, raw_hash: str) -> set[str] | None:
    """Get set of image hashes that share the same raw hash.

    Args:
      raw_hash: raw hash to look up

    Returns:
      Set of image hashes that share the same raw hash, or None if not found

    """
    return set(self._raws[raw_hash]) if raw_hash in self._raws else None

  def Path(self, path: str) -> str | None:
    """Get the image hash that corresponds to the given path.

    Args:
      path: path to look up

    Returns:
      hash of the image that has this path, or None if not found

    """
    try:
      val_path: pathlib.Path = pathlib.Path(path).expanduser().resolve()
    except Exception:  # noqa: BLE001
      return None
    return self._paths.get(str(val_path))

  def Image(self, img_hash: str) -> DBImageType | None:
    """Get the image metadata for the given image hash.

    Args:
      img_hash: image hash to look up

    Returns:
      Image metadata for the given image hash, or None if not found

    """
    return copy.deepcopy(self._db['images'].get(img_hash))

  @property
  def output(self) -> pathlib.Path | None:
    """Get current output directory for generated images.

    Returns:
      pathlib.Path or None if not set

    """
    return pathlib.Path(self._db['image_output_dir']) if self._db['image_output_dir'] else None

  @output.setter
  def output(self, value: pathlib.Path | str | None) -> None:
    """Set current output directory for generated images.

    Args:
      value: pathlib.Path, string path, or None to clear the output directory

    Raises:
      Error: if the provided path is invalid (does not exist or is not a directory)

    """
    path: pathlib.Path | None = (
      pathlib.Path(value).expanduser().resolve() if value is not None else None
    )
    if path is None:
      self._db['image_output_dir'] = None
      logging.info('Cleared DB image output directory')
      return
    if not path.exists() or not path.is_dir():
      raise Error(f'Invalid output directory: {path} (must exist and be a directory)')
    str_path: str = str(path)
    self._db['image_output_dir'] = str_path
    if str_path not in self._db['known_image_sources']:
      self._db['known_image_sources'].append(str_path)  # track this path as a known image source
    logging.info(f'Set DB image output directory to: {path} (also added to known image sources)')

  def Save(self) -> None:
    """Save the database to file.

    Raises:
      Error: if safe_save is enabled and the existing DB on disk differs from the loaded DB

    """
    if self._read_only:
      logging.warning('AIDatabase in read-only mode: will *NOT* save! (would have saved now)')
      return
    with _DB_DISK_LOCK:  # ensure thread-safe save operations
      # check on previous save
      if self._safe_save and self._config.path.exists():
        logging.debug('Safe save enabled, reading existing DB before saving to prevent data loss')
        existing_db: _DBType = cast(
          '_DBType',
          self._config.DeSerialize(
            decryption_key=self._key, unpickler=key.UnpickleJSON, silent=True
          ),
        )
        if (
          existing_db['version'] != self._db['version']
          or existing_db['last_save'] != self._db['last_save']
        ):
          raise Error(
            f'DB on disk {_DBLabel(existing_db)} differs from loaded DB {self.label}, '
            'aborting save to prevent data loss'
          )
      # update DB metadata before saving
      prev_label: str = self.label
      self._db.update(
        {
          'version': self._db['version'] + 1,  # increment DB version on each save
          'db_version': __version__,  # set to current package version on creation
          'last_save': timer.Now(),
        }
      )
      # save the DB to disk with optional encryption and compression
      self._config.Serialize(
        cast('tbase.JSONDict', self._db),
        encryption_key=self._key,
        pickler=key.PickleJSON,
        compress=_DB_COMPRESS_LEVEL if self._compress_save else None,
      )
      logging.info(f'DB saved to {self._config.path}: {prev_label} -> {self.label}')

  def RefreshDBModels(self, api: APIProtocol) -> None:
    """Refresh the DB models by fetching from the API and updating the DB. Does NOT delete models.

    Args:
      api: APIProtocol instance to use for fetching available models

    Raises:
      Error: if there are duplicate models by hash

    """
    models: list[AIModelType] = api.GetModels()
    # add missing hashes
    all_paths: set[str] = {model['path'] for model in self._db['models'].values() if model['path']}
    for model in models:
      if model['path'] in all_paths:
        continue  # skip duplicates by path (we know we have this one), we only want unique models
      if not model['hash'].strip():
        logging.warning(f'Model with empty hash received from API, hashing {model["path"]}')
        model['hash'] = hashes.Hash256(pathlib.Path(model['path']).read_bytes()).hex()
      logging.info(f'Adding model: {model["name"]} -> {model["hash"]}')
      if model['hash'] in self._db['models']:
        raise Error(f'Model {model} already exists in DB {self._db["models"][model["hash"]]}')
      self._db['models'][model['hash']] = model  # add to DB models
    # done, log
    logging.info(f'Refreshed DB models; total models in DB: {len(self._db["models"])}')

  def RefreshDBLora(self, api: APIProtocol) -> None:
    """Refresh the DB lora by fetching from the API and updating the DB. Does NOT delete lora.

    Args:
      api: APIProtocol instance to use for fetching available models

    Raises:
      Error: if there are duplicate lora by hash

    """
    loras: list[AIModelType] = api.GetLora()
    # add missing hashes
    all_paths: set[str] = {model['path'] for model in self._db['lora'].values() if model['path']}
    for lora in loras:
      if lora['path'] in all_paths:
        continue  # skip duplicates by path (we know we have this one), we only want unique models
      if not lora['hash'].strip():
        logging.warning(f'Model with empty hash received from API, hashing {lora["path"]}')
        lora['hash'] = hashes.Hash256(pathlib.Path(lora['path']).read_bytes()).hex()
      try:
        lora['autov3'] = base.AutoV3LoraHash(lora['path'])
      except tbase.Error:
        logging.warning(f'Failed to compute AutoV3 hash for LoRA from SDNext API: {lora["path"]}')
      logging.info(f'Adding lora: {lora["name"]} -> {lora["hash"]}/{lora.get("autov3", "-")}')
      if lora['hash'] in self._db['lora']:
        raise Error(f'Lora {lora} already exists in DB {self._db["lora"][lora["hash"]]}')
      self._db['lora'][lora['hash']] = lora  # add to DB lora
    # done, log
    logging.info(f'Refreshed DB lora; total lora in DB: {len(self._db["lora"])}')

  def GetModelHash(self, model_name: str, *, api: APIProtocol | None = None) -> str:
    """Get the model hash for a given model key. If API is given will also try to fetch.

    Args:
      model_name: The model name to look up
      api: (default None) APIProtocol instance to use for fetching available models automatically;
          if None, it will only search in the existing DB models and will not attempt to fetch

    Returns:
      The model hash corresponding to the given model name

    Raises:
      Error: on error or if the model is not found

    """
    # check the name
    model_name = model_name.lower().strip()
    if not model_name:
      raise Error('Model name cannot be empty')
    # search in DB models
    possible_models: list[AIModelType] = [
      model
      for model in self._db['models'].values()
      if model_name in model['name'].lower() or model_name in model['alias'].lower()
    ]
    if len(possible_models) > 1:
      raise Error(f'Multiple models found matching name "{model_name}": {possible_models}')
    if len(possible_models) == 1:
      return possible_models[0]['hash']  # found unique
    # model not found, we will fetch *all* models, if possible
    if not api:
      raise Error(f'Model with name "{model_name}" not found in DB')  # in this case it's an error!
    logging.warning(f'Model with name "{model_name}" not found in DB, fetching all models from API')
    self.RefreshDBModels(api)
    # we have refreshed the DB models, try searching again
    possible_models = [
      model
      for model in self._db['models'].values()
      if model_name in model['name'].lower() or model_name in model['alias'].lower()
    ]
    if len(possible_models) > 1:
      raise Error(f'Multiple models found matching name "{model_name}": {possible_models}')
    if len(possible_models) == 1:
      return possible_models[0]['hash']  # found unique
    raise Error(
      f'Model with name "{model_name}" not found, try available names: '
      f'{[model["name"] for model in self._db["models"].values()]}'
    )

  def GetModel(self, model_hash: str) -> AIModelType:
    """Get the model metadata for a given model hash.

    Args:
      model_hash: The model hash to look up

    Returns:
      The AIModelType metadata corresponding to the given model hash

    Raises:
      Error: if the model hash is not found in the DB

    """
    if model_hash not in self._db['models']:
      raise Error(f'Model with hash {model_hash!r} not found in DB')
    return copy.deepcopy(self._db['models'][model_hash])

  def QueryNormalize(self, meta: AIMetaType) -> AIMetaType:
    """Normalize an AIMetaType for consistent hashing and comparison.

    Args:
      meta: The AIMetaType to normalize

    Returns:
      A new AIMetaType with normalized fields.

    """
    # make a copy to modify without affecting caller
    meta = copy.deepcopy(meta)
    # inject lora info into meta
    lora_weights: dict[str, tuple[str, str]] = base.LoraExtract(
      meta['positive'] + '\n' + (meta['negative'] or '')
    )
    meta['lora'] = {} if lora_weights else None
    for lora_name, (_, weights) in lora_weights.items():
      lora_hash: str = base.FindModelHash('lora', '', lora_name, _ModelsRef(self._db['lora']))
      meta['lora'][lora_hash] = weights  # type: ignore[index]
    return meta

  def Txt2Img(
    self,
    meta: AIMetaType,
    api: APIProtocol,
    *,
    redo: bool = False,
    tm: int | None = None,
  ) -> tuple[DBImageType, bytes]:
    """Generate image from text prompt, store in DB.

    Beware that with no self.output the image will NOT be added to the DB (no path to track).

    Args:
      meta: AIMetaType object containing the generation metadata (e.g., prompt, steps,
          seed, width, height, sampler_id, model_key)
      api: APIProtocol instance to use for making the API call
      redo: (default False) If True, forces re-generation of the image even if it exists in the DB
      tm: (default: None) Optional timestamp to use for the generated image metadata;
          if None, uses time we  get image back from API

    Returns:
      A tuple containing the DBImageType object and the raw image data.
      The returned object in NOT the same object in the DB, the DB has a copy.

    Raises:
      Error: if the model hash in meta is not found in the DB models

    """
    meta = self.QueryNormalize(meta)  # this will, for example, add the lora info to the meta
    # we have the model?
    if meta['model_hash'] not in self._db['models']:
      raise Error(f'Model with hash {meta["model_hash"]} not found in DB models')
    # try to find it here already
    db_entry: DBImageType
    for h, db_entry in self._db['images'].items():
      for p, path_info in db_entry['paths'].items():
        if path_info['ai_meta'] == meta:
          # we have a file that matches, or should have...
          logging.warning(f'Found existing {h!r} image with matching metadata at {p}: {db_entry}')
          if not pathlib.Path(p).exists():
            logging.error(f'Missing image {p}, will not use it...')
            continue
          # file matches and exists
          if redo:
            logging.warning(f'REDOING image generation for metadata match at {p}!...')
            continue
          # we do not have to re-do
          return (db_entry, pathlib.Path(p).read_bytes())
    # not found or redo requested, generate new
    img_bytes: bytes
    db_entry, img_bytes = api.Txt2Img(
      self._db['models'][meta['model_hash']].copy(), meta, dir_root=self.output, tm=tm
    )
    hsh: str = db_entry['hash']
    path: str = next(iter(db_entry['paths']))  # get the first path from the entry paths
    if self.output and path:
      if hsh in self._db['images']:
        obj: DBImageType = self._db['images'][hsh]
        obj['paths'][path] = copy.deepcopy(db_entry['paths'][path])  # add the new path
        # no new hash, so no new raw_hash, so that index is OK; just add the new path
      else:
        # new image
        db_entry['paths'][path]['main'] = True  # mark this path as main for the image
        self._db['images'][hsh] = copy.deepcopy(db_entry)  # add to DB images
        # add to indexes
        self._raws.setdefault(db_entry['raw_hash'], set()).add(hsh)
      self._paths[path] = hsh  # add to path index
    return (db_entry, img_bytes)

  def Reproduce(self, img_hash: str, api: APIProtocol) -> tuple[DBImageType, bytes]:  # noqa: C901, PLR0912
    """Reproduce an image by its hash, using the metadata in the DB.

    Args:
      img_hash: The hash of the image to reproduce
      api: APIProtocol instance to use for making the API call

    Returns:
      A tuple containing the new DBImageType object and the raw image data.

    Raises:
      Error: on error

    """
    if img_hash not in self._db['images']:
      raise Error(f'Image with hash {img_hash!r} not found in DB')
    old_entry: DBImageType = self._db['images'][img_hash]
    metas: list[DBImagePathType] = [o for o in old_entry['paths'].values() if o['ai_meta']]
    if not metas:
      raise Error(f'Image with hash {img_hash!r} does not have any AI metadata, cannot reproduce')
    if len(metas) > 1:  # TODO: can we do better?
      logging.error(f'Image {img_hash!r} has multiple meta: {metas}, using the first one')
    meta: AIMetaType = copy.deepcopy(metas[0]['ai_meta'])  # type: ignore[assignment]
    logging.info(f'Reproducing image {img_hash!r} with metadata: {meta}')
    # we have the model?
    if meta['model_hash'] not in self._db['models']:
      raise Error(f'Model with hash {meta["model_hash"]} not found in DB models')
    # show the errors
    for err in sorted(metas[0]['parse_errors'] or []):
      logging.error(f'Image parsing error: {err}')
      if err == 'upscaled':
        raise Error(f'Image upscaled; use original size: {old_entry}')
    # show lora/lycoris problems
    if meta['lora']:
      for h, w in meta['lora'].items():
        if h not in self._db['lora']:
          logging.error(f'Image lora error: missing {h!r}')
        if '@' in w or ',' in w:
          logging.error(f'Image lora A1111-style weights: {w!r}')
    # try to reproduce
    new_entry: DBImageType
    img_bytes: bytes
    new_entry, img_bytes = api.Txt2Img(
      self._db['models'][meta['model_hash']].copy(), meta, dir_root=self.output
    )
    hsh: str = new_entry['hash']
    path: str = next(iter(new_entry['paths']))  # get the first path from the entry paths
    if self.output and path:
      if hsh in self._db['images']:
        obj: DBImageType = self._db['images'][hsh]
        obj['paths'][path] = copy.deepcopy(new_entry['paths'][path])  # add the new path
        # no new hash, so no new raw_hash, so that index is OK; just add the new path
      else:
        # new image
        new_entry['paths'][path]['main'] = True  # mark this path as main for the image
        self._db['images'][hsh] = copy.deepcopy(new_entry)  # add to DB images
        # add to indexes
        self._raws.setdefault(new_entry['raw_hash'], set()).add(hsh)
      self._paths[path] = hsh  # add to path index
    if new_entry['raw_hash'] == old_entry['raw_hash']:
      logging.info(f'Successful raw match {new_entry["raw_hash"]!r} for reproduction')
    else:
      logging.error(f'New image raw {new_entry["raw_hash"]!r} != {old_entry["raw_hash"]!r}')
    return (new_entry, img_bytes)

  def Sync(self, *, add_dir: pathlib.Path | str | None = None, redo: bool = False) -> None:  # noqa: C901, PLR0914, PLR0915
    """Go over all known image dirs, check for new/deleted images, update DB accordingly.

    Re-computes hashes for all images, but if hash is know does not re-parse it,
    just updates the paths if needed. If redo is True, it will re-parse all images
    even if the hash is known.

    Args:
      add_dir: (default None) Optional additional dir to add to known image sources and sync with
      redo: (default False) If True, forces re-sync of all images

    Raises:
      Error: if the provided path is invalid or other errors

    """
    add_dir = pathlib.Path(add_dir).expanduser().resolve() if add_dir else None
    if add_dir and (not add_dir.exists() or not add_dir.is_dir()):
      raise Error(f'Provided directory for sync does not exist: {add_dir}')
    # add the new dir to known sources if not already present
    if add_dir:
      str_add_dir: str = str(add_dir)
      if str_add_dir not in self._db['known_image_sources']:
        self._db['known_image_sources'].append(str_add_dir)
        logging.info(f'Added new image source dir: {add_dir}')
    # scan all known source dirs for image files
    is_target: abc.Callable[[pathlib.Path], bool] = lambda p: (
      p.suffix.lower() in _EXTENSIONS_TO_PARSE_LOWER and p.is_file()
    )
    files_todo: list[pathlib.Path] = []
    valid_sources: int = 0
    invalid_sources: int = 0
    for dir_path in sorted(pathlib.Path(d) for d in self._db['known_image_sources']):  # determinism
      # check the source dir exists and is a directory
      if not dir_path.exists() or not dir_path.is_dir():
        logging.error(f'Known image source dir does not exist, skipping: {dir_path}')
        invalid_sources += 1
        continue
      # we have a valid source dir, scan for images
      filtered_dir: list[pathlib.Path] = [p for p in sorted(dir_path.rglob('*')) if is_target(p)]
      files_todo.extend(filtered_dir)  # add the sorted (for determinism) list of files to the todo
      valid_sources += 1
      logging.info(f'Valid source dir with {len(filtered_dir)} images added: {dir_path}')
    logging.info(
      f'Found {len(files_todo)} total image files to sync from {valid_sources} valid dir sources '
      f'(skipped {invalid_sources} invalid sources)'
    )
    # now go over them with a progress bar, confident they are valid, and update the DB accordingly
    valid_image: int = 0
    invalid_image: int = 0
    new_image: int = 0
    meta_error: int = 0
    img_error: int = 0
    all_models: dict[str, str] = _ModelsRef(self._db['models'])
    all_lora: dict[str, str] = _ModelsRef(self._db['lora'])
    Image.MAX_IMAGE_PIXELS = 500_000_000  # set a high limit to avoid DecompressionBombError
    with timer.Timer(emit_log=False) as tmr_add:
      for img_path in tqdm.tqdm(
        iterable=files_todo,
        total=len(files_todo),  # strictly not necessary, but helps if need to enumerate() for debug
        desc='Read',
        unit='img',
        dynamic_ncols=True,
        smoothing=0.001,
        colour='green',
      ):
        # try to read the file and hash it: we recompute the hash no matter what
        try:
          img_bytes: bytes = img_path.read_bytes()
        except OSError:
          logging.error(f'Cannot read image file, skipping: {img_path}')
          invalid_image += 1
          continue
        img_hash: str = hashes.Hash256(img_bytes).hex()
        valid_image += 1
        str_path: str = str(img_path)
        # do we know this hash?
        if (
          not redo  # respect re-do
          and img_hash in self._db['images']  # we have the hash
          and str_path in self._db['images'][img_hash]['paths']  # and we have this path
        ):
          continue  # already known — update path tracking if needed
        # new image (or redo) — parse metadata and add to DB
        try:
          new_entry: DBImageType = _ImportImageFile(
            img_path, img_bytes, img_hash, all_models, all_lora
          )
        except (ValueError, tbase.Error) as err:
          img_error += 1
          logging.error(f'Could not import image, skipping {img_path}: {err}')
          continue
        # we have a new entry, add to DB
        new_image += 1
        if new_entry['paths'][str_path]['parse_errors']:
          meta_error += 1
        if img_hash in self._db['images']:
          self._db['images'][img_hash]['paths'][str_path] = new_entry['paths'][str_path]
        else:
          self._db['images'][img_hash] = new_entry
        logging.debug(f'Imported new image {img_hash[:12]}: {img_path}')
    # done, log
    logging.info(
      f'Sync done in {tmr_add}: {len(self._db["images"])} unique hashes in DB. '
      f'Scanned {valid_sources} dir sources containing {valid_image} valid images and '
      f'{invalid_image} invalid images; of these, {new_image} were new and added to the DB, '
      f'{meta_error} had metadata errors, {img_error} had irrecoverable errors and were ignored. '
      'Now checking for deleted images...'
    )
    # done, recompute indexes
    self._ComputeIndexes()


_ModelsRef: abc.Callable[[dict[str, AIModelType]], dict[str, str]] = lambda m: {
  # we include the autov3 hash in the key if it's present, to help disambiguate find lora/lyco
  # note: base.FindModelHash() expects the '.' separator and uses it to remove and return the
  # actual hash
  f'{h}{"." + v["autov3"] if v["autov3"] else ""}': f'{v["name"]} {v["alias"]}'
  for h, v in m.items()
}


_PARAMS_LINE_RE: re.Pattern[str] = re.compile(
  r'^(Steps|Sampler|CFG scale|Seed|Size|Model)\s*:', re.IGNORECASE
)
_PARAM_SPLIT_RE: re.Pattern[str] = re.compile(r',\s*(?=[A-Za-z][A-Za-z0-9 _]*:)', re.IGNORECASE)


def ParseImageMetadata(info_text: str) -> dict[str, str]:  # noqa: C901, PLR0912, PLR0914
  """Parse SDNext/A1111 image metadata string into a key-value dict.

  The metadata string has the structure::

    positive prompt text
    Negative prompt: negative prompt text
    Steps: 10, Size: 256x256, Sampler: DPM++ SDE, ..., Seed: 666, Model hash: abc123, ...

  Args:
    info_text: The raw metadata string from PIL ``img.info``.

  Returns:
    A dict with lowercase keys including ``'positive'``, ``'negative'`` (may be ``None``/absent),
    plus all the comma-separated key-value pairs in lowercase with stripped values.
    Size is split into ``'width'`` and ``'height'``.

  """
  lines: list[str] = info_text.strip().split('\n')
  result: dict[str, str] = {}
  # gather positive prompt lines until we hit the negative or params line
  positive_lines: list[str] = []
  remainder: str = ''
  for i, line in enumerate(lines):
    if line.startswith('Negative prompt:'):
      # everything from here on is remainder to parse; preserve newlines for later splitting
      remainder = '\n'.join([line, *lines[i + 1 :]])
      break
    # check if this line looks like a params line (starts with a known keyword + colon + number)
    if _PARAMS_LINE_RE.match(line):
      remainder = ' '.join(lines[i:])
      break
    positive_lines.append(line)
  else:
    # no break — all lines are prompt
    remainder = ''
  result['positive'] = '\n'.join(positive_lines).strip()
  # split remainder into negative prompt and params
  if remainder.startswith('Negative prompt:'):
    # do NOT strip before splitting — we need '\n' separators preserved (e.g. empty negative)
    neg_and_params: str = remainder[len('Negative prompt:') :]
    # the negative prompt may span multiple lines; consume lines until we hit a params line,
    # mirroring the same logic used for the positive prompt above
    neg_lines: list[str] = neg_and_params.split('\n')
    negative_parts: list[str] = []
    params_start: int = len(neg_lines)  # default: all lines belong to negative
    for j, neg_line in enumerate(neg_lines):
      if _PARAMS_LINE_RE.match(neg_line):
        params_start = j
        break
      negative_parts.append(neg_line)
    result['negative'] = '\n'.join(negative_parts).strip()
    remainder = ' '.join(neg_lines[params_start:]) if params_start < len(neg_lines) else ''
  # parse comma-separated key: value pairs from remainder
  # we can't just split on ',' because values may contain commas (model names, etc.)
  # instead we split on ', <Key>:' boundaries using regex
  param_text: str = remainder.strip()
  if param_text:
    # split on boundaries where ', Word:' or ', Word Word:' appear
    parts: list[str] = _PARAM_SPLIT_RE.split(param_text)
    for part in parts:
      if ':' not in part:
        continue
      k, _, v = part.partition(':')
      key_norm: str = k.strip().lower()
      val_norm: str = v.strip()
      if key_norm == 'size':
        # split 'WxH' or 'W x H' into separate keys
        size_match: re.Match[str] | None = re.match(r'(\d+)\s*[xX]\s*(\d+)', val_norm)
        if size_match:
          result['width'] = size_match.group(1)
          result['height'] = size_match.group(2)
      else:
        result[key_norm] = val_norm
  # done
  return result


def _ImportImageFile(  # noqa: C901, PLR0912, PLR0914, PLR0915
  img_path: pathlib.Path,
  img_bytes: bytes,
  img_hash: str,
  models: dict[str, str],
  loras: dict[str, str],
) -> DBImageType:
  """Parse an image file from disk and create a DBImageType entry.

  Supports SDNext/A1111 PNG metadata in ``img.info['parameters']`` or
  ``img.info['UserComment']``.

  Args:
    img_path: Path to the image file.
    img_bytes: Raw bytes of the image file (already read).
    img_hash: Precomputed SHA-256 hex digest of the file bytes.
    models: The DB models like {hash: model_name/alias}.
    loras: The DB loras like {hash: lora_name/alias}.

  Returns:
    A populated DBImageType for the image.

  Raises:
    Error: unsupported format or AI incomplete image

  """
  # open image from buffer
  fmt, width, height, raw_hash, info_text = base.GetBasicDataFromImage(img_bytes)
  # we have the metadata text, first check it is an AI image
  if not info_text:
    # could not find metadata, we consider this a non-AI image
    return DBImageType(
      hash=img_hash,
      raw_hash=raw_hash,
      size=len(img_bytes),
      width=width,
      height=height,
      format=fmt.value,
      info=None,
      paths={
        str(img_path): DBImagePathType(
          main=False,
          created_at=base.GetFileCreation(img_path),
          origin=None,
          parse_errors=None,
          version=None,
          ai_meta=None,
          sd_info=None,
          sd_params=None,
        )
      },
    )
  # parse metadata
  meta_raw: dict[str, str] = ParseImageMetadata(info_text)
  parse_errors: dict[str, None] = {}
  # resolve model hash
  model_hash: str | None = None
  try:
    model_hash = base.FindModelHash(
      'model', meta_raw.get('model hash', ''), meta_raw.get('model', ''), models
    )
  except base.Error as err:
    parse_errors[str(err)] = None  # TODO: solve problem of too many missing models
  # resolve loras, if present
  lora_info: dict[str, str] = {}
  lora_weights: dict[str, tuple[str, str]] = base.LoraExtract(info_text)
  unknown_lora: int = 0
  lora_hash: str
  name: str
  if 'lora hashes' in meta_raw:
    # we have a list of 'hash: name' pairs to base on, so we get the hashes to do reliable matching
    for lora in meta_raw['lora hashes'].lower().replace('"', '').split(','):
      if not lora.strip():
        continue  # skip empty entries
      name, hash_part = lora.strip().split(':')
      name, hash_part = name.strip(), hash_part.strip()
      weights: str = lora_weights.get(name, ('', ''))[1]
      if not weights:
        parse_errors[f'missing weights for lora #{hash_part}/{name}'] = None
      try:
        lora_hash = base.FindModelHash('lora', hash_part, name, loras)
      except base.Error as err:
        parse_errors[str(err)] = None
        unknown_lora += 1
        lora_hash = f'unknown-{unknown_lora}-{name}-{hash_part}'
      lora_info[lora_hash] = weights
  elif lora_weights or 'lora networks' in meta_raw:
    # if we have 'lora networks' (a SDNext thing) we have the names but not the hashes
    for lora in meta_raw.get('lora networks', '').lower().replace('"', '').split(','):
      name = lora.strip()
      if not name or name in lora_weights:
        continue  # we have this one already from the weights parsing (or empty entry)
      lora_weights[name] = ('lora', '')
    # we don't have the hashes, but we have the names from the query, so we try that...
    for name, (_, weights) in lora_weights.items():
      try:
        lora_hash = base.FindModelHash('lora', '', name, loras)
      except base.Error as err:
        parse_errors[str(err)] = None
        unknown_lora += 1
        lora_hash = f'unknown-{unknown_lora}-{name}-nohash'
      lora_info[lora_hash] = weights
  elif 'lora' in (info_lower := info_text.lower()) or 'lyco' in info_lower:
    # there is some lora info we couldn't parse (possibly: could be word like "floral")
    parse_errors['lora/lyco possible unparsed info'] = None
  # get version
  img_origin: ImageOrigin | None = None
  app_version: str | None = None
  empty_query_parser: str = base.SD_EMPTY_QUERY_PARSER
  if meta_raw.get('version'):
    if meta_raw.get('app', '').lower() == 'sd.next':
      # if loading through here, SDNext undistinguishable from TransNext
      img_origin, app_version = ImageOrigin.SDNext, meta_raw['version']
      empty_query_parser = base.QueryParser.SDNextNative.value
    else:
      img_origin, app_version = ImageOrigin.A1111, meta_raw['version']
      empty_query_parser = base.QueryParser.A1111.value
  # build metadata for DB entry, using defaults if parsing fails or fields are missing
  # create helper methods that save the errors to `parse_errors`

  def _IntKey(key: str, default: int, *, empty: str | None = None) -> int:
    try:
      return int(meta_raw.get(key, empty or ('no ' + key)))
    except ValueError as err:
      parse_errors[f'{key}: {err} -> {default}'] = None
      return default

  def _FloatKey(
    data: dict[str, str], key: str, default: int, *, empty: str | None = None, conversion: int = 10
  ) -> int:
    try:
      return round(float(data.get(key, empty or ('no ' + key))) * conversion)
    except ValueError as err:
      parse_errors[f'{key}: {err} -> {default}'] = None
      return default

  def _EnumKey[T: enum.Enum](
    tp: type[T], key: str, default: T | None, *, empty: str | None = None
  ) -> T | None:
    try:
      return tp(meta_raw.get(key, empty or ('no ' + key)))
    except ValueError as err:
      parse_errors[f'{key}: {err} -> {default.value if default else "None"}'] = None
      return default

  # parse a bunch of properties
  v_seed: int = _IntKey('variation seed', -1, empty=base.SD_EMPTY_V_SEED)
  v_strength: int = _FloatKey(
    meta_raw, 'variation strength', 0, empty=base.SD_EMPTY_V_STRENGTH, conversion=100
  )
  sampler: base.Sampler | None = _EnumKey(base.Sampler, 'sampler', base.Sampler.Euler_A)
  parser: base.QueryParser | None = _EnumKey(
    base.QueryParser, 'parser', base.SD_DEFAULT_QUERY_PARSER, empty=empty_query_parser
  )
  assert sampler, '`sampler` has default, this should never happen'  # noqa: S101
  assert parser, '`parser` has default, this should never happen'  # noqa: S101
  sch_sigma: base.SchedulerSigma | None = _EnumKey(
    base.SchedulerSigma, 'sampler sigma', None, empty='default'
  )
  sch_spacing: base.SchedulerSpacing | None = _EnumKey(
    base.SchedulerSpacing, 'sampler spacing', None, empty='default'
  )
  sch_beta: base.SchedulerBeta | None = _EnumKey(
    base.SchedulerBeta, 'sampler beta schedule', None, empty='default'
  )
  sch_type: base.SchedulerPredictionType | None = _EnumKey(
    base.SchedulerPredictionType, 'sampler type', None, empty='default'
  )
  # img2img
  img2img: AIImg2ImgType | None = None
  if (
    meta_raw.get('operations', '').lower() == 'img2img'
    or 'img2img' in info_text.lower()
    or meta_raw.get('denoising strength')  # A1111 would only leave this clue
  ):
    img2img = AIImg2ImgType(
      input_hash=None,  # i think we can never tell unless we did it ourselves
      denoising=_FloatKey(
        meta_raw, 'denoising strength', base.SD_DEFAULT_DENOISING, conversion=100
      ),
    )
  # parse FreeU settings from metadata if present (format: "b1=1.05 b2=1.1 s1=0.55 s2=0.45")
  freeu: AIMetaFreeUType | None = None
  if freeu_str := (meta_raw.get('freeu', '') or '').strip():
    freeu_parts: dict[str, str] = {
      k.strip().lower(): v.strip()
      for part in freeu_str.split()
      if '=' in part
      for k, v in [part.split('=', 1)]
    }
    freeu = AIMetaFreeUType(
      b1=_FloatKey(freeu_parts, 'b1', base.SD_DEFAULT_FREEU_B1, empty='1.0', conversion=100),
      b2=_FloatKey(freeu_parts, 'b2', base.SD_DEFAULT_FREEU_B2, empty='1.0', conversion=100),
      s1=_FloatKey(freeu_parts, 's1', base.SD_DEFAULT_FREEU_S1, empty='1.0', conversion=100),
      s2=_FloatKey(freeu_parts, 's2', base.SD_DEFAULT_FREEU_S2, empty='1.0', conversion=100),
    )
  # build the AIMetaType with the parsed and validated properties
  ai_meta: AIMetaType = AIMetaType(
    # MANDATORY FIELDS (must be present and valid, otherwise we consider this image as malformed)
    model_hash=model_hash,
    positive=meta_raw.get('positive', ''),
    seed=_IntKey('seed', -1),
    v_seed=(
      AIMetaVariationSeedType(seed=v_seed, percent=v_strength)
      if v_seed > 0 and 0 < v_strength <= 100  # noqa: PLR2004
      else None
    ),
    width=width,
    height=height,
    steps=_IntKey('steps', 0),
    cfg_scale=_FloatKey(meta_raw, 'cfg scale', 0),
    sampler=sampler.value,
    # OPTIONAL FIELDS (if missing will have defaults, but if present must be valid)
    negative=meta_raw.get('negative') or None,
    cfg_end=_FloatKey(meta_raw, 'cfg end', 0, empty=base.SD_EMPTY_CFG_END),
    cfg_rescale=_FloatKey(
      meta_raw,
      'cfg rescale',
      base.SD_DEFAULT_CFG_RESCALE,
      empty=base.SD_EMPTY_CFG_RESCALE,
      conversion=100,
    ),
    parser=parser.value,
    clip_skip=_FloatKey(meta_raw, 'clip skip', 0, empty=base.SD_EMPTY_CLIP_SKIP),
    sch_sigma=sch_sigma.value if sch_sigma and sch_sigma != base.SchedulerSigma.default else None,
    sch_spacing=(
      sch_spacing.value if sch_spacing and sch_spacing != base.SchedulerSpacing.default else None
    ),
    sch_beta=sch_beta.value if sch_beta and sch_beta != base.SchedulerBeta.default else None,
    sch_type=(
      sch_type.value if sch_type and sch_type != base.SchedulerPredictionType.default else None
    ),
    ngms=_FloatKey(meta_raw, 'ngms', 0, empty='0', conversion=100) or None,
    cfg_skip=_FloatKey(meta_raw, 'skip early cfg', 0, empty='0', conversion=100) or None,
    lora=lora_info,
    img2img=img2img,
    freeu=freeu,
  )
  # do more checks; be strict
  # SEED
  if not 0 < ai_meta['seed'] <= base.SD_MAX_SEED:
    parse_errors['`seed` out of bounds'] = None
  # DIMENSIONS
  meta_width = int(meta_raw.get('width', 'no width'))
  meta_height = int(meta_raw.get('height', 'no height'))
  if meta_width != width or meta_height != height:
    meta_px: int = meta_width * meta_height
    actual_px: int = width * height
    if meta_px and actual_px and meta_px < actual_px and actual_px / meta_px > 1.5:  # noqa: PLR2004
      # the hallmark of a img->img upscaler: actual >> meta, and a significant difference
      parse_errors['upscaled'] = None
    elif (
      meta_width  # noqa: PLR0916
      and meta_height
      and (meta_width % 8 or meta_height % 8)
      and not width % 8
      and not height % 8
      and actual_px
      and meta_px > actual_px
      and meta_px / actual_px < 1.1  # noqa: PLR2004
    ):
      # the hallmark of an image that had its dimensions corrected to be a multiple of 8:
      # meta is not a multiple, but actual is, and they are super close in dimensions
      parse_errors['size corrected / 8'] = None
    else:
      extra_msg: str = '; probably an unfinished image' if meta_px > actual_px else ''
      raise Error(f'Dim error: {meta_width} x {meta_height} / {width} x {height}{extra_msg}')
  # STEPS, CFG SCALE, CFG END, CLIP SKIP
  if not 1 <= ai_meta['steps'] <= base.SD_MAX_ITERATIONS:
    parse_errors['`steps` out of bounds'] = None
  if not 10 <= ai_meta['cfg_scale'] <= base.SD_MAX_CFG_SCALE:  # noqa: PLR2004
    parse_errors['`cfg_scale` out of bounds'] = None
  if not 0 <= ai_meta['cfg_end'] <= 10:  # noqa: PLR2004
    parse_errors['`cfg_end` out of bounds'] = None
  if not 10 <= ai_meta['clip_skip'] <= base.SD_MAX_CLIP_SKIP:  # noqa: PLR2004
    parse_errors['`clip_skip` out of bounds'] = None
  # join everything together into the DBImageType
  if parse_errors:
    logging.debug(f'Parsed image metadata with errors: {info_text}, errors: {parse_errors}')
  return DBImageType(
    hash=img_hash,
    raw_hash=raw_hash,
    size=len(img_bytes),
    width=width,
    height=height,
    format=fmt.value,
    info=info_text,
    paths={
      str(img_path): DBImagePathType(
        main=False,
        created_at=base.GetFileCreation(img_path),
        origin=img_origin.value if img_origin else ImageOrigin.AIUnknown.value,  # we could parse!
        parse_errors=parse_errors or None,
        version=app_version,
        ai_meta=ai_meta,
        sd_info=None,
        sd_params=None,
      )
    },
  )


def _DBLabel(db: _DBType) -> str:
  """Get a human-readable label for the database, for logging and display purposes.

  Returns:
    string '#<N>@<tm>'

  """
  return f'#{db["version"]}@{timer.TimeStr(db["last_save"])}'


@runtime_checkable
class APIProtocol(Protocol):
  """SDNext API protocol contract needed by the DB."""

  @abstract.abstractmethod
  def GetModels(self) -> list[AIModelType]:
    """Get list of available models from SDNext API.

    Returns:
      A list of AIModelType objects representing the available models. BEWARE: hash may be ''!

    Raises:
      Error: If there is an error with the API call or if the response is invalid.

    """

  @abstract.abstractmethod
  def GetLora(self) -> list[AIModelType]:
    """Get list of available lora/lycoris from SDNext API.

    Returns:
      A list of AIModelType objects representing the available lora/lycoris. BEWARE: hash will be ''

    Raises:
      Error: If there is an error with the API call or if the response is invalid.

    """

  @abstract.abstractmethod
  def Txt2Img(
    self,
    model: AIModelType,
    meta: AIMetaType,
    *,
    dir_root: pathlib.Path | None = None,
    tm: int | None = None,
  ) -> tuple[DBImageType, bytes]:
    """Generate image from text prompt using SDNext API.

    Args:
      model: AIModelType object representing the model to use for generation
      meta: AIMetaType object containing the generation metadata (e.g., prompt, steps,
          seed, width, height, sampler_id, model_key)
      dir_root: (default: None) Directory root to save the generated image, if None don't save
      tm: (default: None) Optional timestamp to use for the generated image metadata;
          if None, uses time we  get image back from API

    Returns:
      A tuple containing the DBImageType object and the raw image data.

    Raises:
      Error: If there is an error with the API call, if the response is invalid,
          or if the image data is invalid.

    """
