# SPDX-FileCopyrightText: Copyright 2026 Daniel Balparda <balparda@github.com>
# SPDX-License-Identifier: Apache-2.0
"""TransNext core database module."""

from __future__ import annotations

import abc as abstract
import enum
import io
import logging
import pathlib
import re
import threading
from collections import abc
from typing import Protocol, Self, TypedDict, cast, runtime_checkable

import tqdm
from PIL import Image
from transcrypto.core import aes, hashes, key
from transcrypto.utils import base as tbase
from transcrypto.utils import config as app_config
from transcrypto.utils import timer

from transnext import __version__
from transnext.core import base

_DB_COMPRESS_LEVEL = 5  # default compression level for DB saving
_DB_DISK_LOCK: threading.Lock = threading.Lock()  # lock for thread-safe DB operations


class Error(base.Error):
  """TransNext DB exception."""


class _DBType(TypedDict):
  """DB object type.

  Should be suitable for JSON and pickle serialization, so no complex types or custom classes.
  Don't use sets.
  """

  version: int  # DB version; increment on save
  db_version: str  # package version (transnext.__version__) at time of last save
  last_save: int  # timestamp of last save
  images: dict[str, DBImageType]  # {image_hash: image_metadata}
  models: dict[str, AIModelType]  # {model_hash: model}
  known_image_sources: list[str]  # places to track images from
  image_output_dir: str | None  # current directory to save generated images to


def _DBTypeFactory(overrides: dict[str, object] | None = None) -> _DBType:
  """Create new _DBType object with default values.

  Returns:
    A new _DBType object with default values.

  """
  obj: _DBType = {
    'version': 0,
    'db_version': __version__,  # set to current package version on creation
    'last_save': timer.Now(),
    'images': {},
    'models': {},
    'known_image_sources': [],
    'image_output_dir': None,
  }
  obj.update(overrides or {})  # type: ignore[typeddict-item]
  return obj


class ImageOrigin(enum.Enum):
  """Image origin enum."""

  A1111 = 'A1111'  # generated by Automatic1111, could be from other sources
  SDNext = 'SDNext'  # generated by SDNext, could be from other sources
  TransNext = 'TransNext'  # generated by this software, via SDNext API
  AIUnknown = 'AIUnknown'  # we could parse the metadata, but could not specify the origin


class ImageFormat(enum.Enum):
  """Image format enum."""

  JPEG = 'JPEG'
  PNG = 'PNG'
  GIF = 'GIF'


_PIL_FORMAT_MAP: dict[str, ImageFormat] = {
  'JPEG': ImageFormat.JPEG,
  'PNG': ImageFormat.PNG,
  'GIF': ImageFormat.GIF,
}

_EXTENSIONS_TO_PARSE_LOWER: set[str] = {'.png', '.jpg', '.jpeg', '.gif'}


class DBImageType(TypedDict):
  """DB image metadata type."""

  hash: str  # image hash: the hash of the file on disk, usually a PNG file
  raw_hash: str  # raw image hash: the hash of the raw image data computed internally to PIL
  path: str | None  # image file path
  alt_path: list[str]  # alternative paths where the image is found (e.g., duplicates)
  size: int  # image file size
  width: int  # image width
  height: int  # image height
  format: str  # ImageFormat string (e.g., JPEG, PNG, GIF)
  created_at: int  # timestamp of when the image was added to the DB
  origin: str | None  # ImageOrigin of the image, if known, otherwise None
  version: str | None  # version of the software that generated the image, if known, otherwise None
  ai_meta: AIMetaType | None  # AI generation metadata; None: not an AI-gen image we could parse
  sd_info: tbase.JSONDict  # additional info from SDNext API response
  sd_params: tbase.JSONDict  # additional info from SDNext API response
  parse_errors: list[str]  # any errors encountered during parsing of the image metadata


class AIModelType(TypedDict):
  """AI model metadata type."""

  hash: str  # hash of the model file
  name: str  # AI model identifier
  path: str  # path to the model file
  type: str  # model file type (e.g., 'safetensors', 'ckpt')
  description: str | None  # brief description of the model's capabilities


class AIMetaType(TypedDict):
  """AI image metadata.

  This is supposed to hold all the options this software handles that affects image generation,
  so that we can later on use it for filtering and searching images by these parameters.
  It should be complete enough to allow us to reproduce the generation of the image.

  Keep it shallow and simple, only primitive types, no complex objects or custom classes,
  to ensure it is comparable and serializable without issues.

  No dict, no list. If we add that we'll have to implement custom comparison.
  """

  model_hash: str | None  # AI model hash (only None if we could not parse/find the model)
  positive: str  # positive prompt used for AI processing
  negative: str | None  # negative prompt used for AI processing
  seed: int  # seed used in AI processing
  v_seed: tuple[int, int] | None  # (variation seed, percent) or None if not used; *100 int storage
  width: int  # image width
  height: int  # image height
  steps: int  # number of steps used in AI processing
  cfg_scale: int  # CFG scale used in AI processing (guidance scale, times 10 for int storage)
  cfg_end: int  # CFG end step used in AI processing (times 10 for int storage)
  sampler: str  # base.Sampler string used in AI processing
  parser: str  # base.QueryParser string used for the prompts
  clip_skip: int  # CLIP skip used in AI processing (times 10 for int storage)
  # TODO: 'sampler beta schedule': 'scaled', / 'schedulers_beta_schedule'
  # TODO: 'sampler sigma': 'karras', / 'schedulers_sigma'
  # TODO: 'sampler spacing': 'linspace', / 'schedulers_timestep_spacing'
  # TODO: 'sampler type': 'epsilon', / 'schedulers_prediction_type'


def AIMetaTypeFactory(overrides: dict[str, object] | None = None) -> AIMetaType:
  """Create new AIMetaType object with default values.

  SPECIAL CASE: seed in {None, -1, 0} will NOT overwrite, will generate a random seed!
  SPECIAL CASE: v_seed in {None, -1, 0} and strength>0 will NOT overwrite, will generate random seed

  Returns:
    A new AIMetaType object with default values.

  Raises:
    Error: if the resulting seed/v_seed value is invalid (not in the range 0 < s ≤ base.SD_MAX_SEED)

  """
  obj: AIMetaType = AIMetaType(
    model_hash=None,
    positive='',
    negative=None,
    seed=-1,  # start with random flag
    v_seed=None,
    width=base.SD_DEFAULT_WIDTH,
    height=base.SD_DEFAULT_HEIGHT,
    steps=base.SD_DEFAULT_ITERATIONS,
    sampler=base.SD_DEFAULT_SAMPLER.value,
    parser=base.SD_DEFAULT_QUERY_PARSER.value,
    cfg_scale=base.SD_DEFAULT_CFG_SCALE,
    cfg_end=base.SD_DEFAULT_CFG_END,
    clip_skip=base.SD_DEFAULT_CLIP_SKIP,
  )
  obj.update(overrides or {})  # type: ignore[typeddict-item]
  # make sure seed is actually set now
  obj['seed'] = base.SeedGen() if obj['seed'] in {None, -1, 0} else obj['seed']
  if not 0 < obj['seed'] <= base.SD_MAX_SEED:
    raise Error(f'Invalid `seed` value in AIMetaType: {obj}')
  if obj['v_seed'] is not None and obj['v_seed'][0] in {None, -1, 0} and obj['v_seed'][1] > 0:
    obj['v_seed'] = (base.SeedGen(), obj['v_seed'][1])  # type: ignore[typeddict-item]
  if obj['v_seed'] is not None and not 0 < obj['v_seed'][0] <= base.SD_MAX_SEED:
    raise Error(f'Invalid `v_seed` value in AIMetaType: {obj}')
  # done
  return obj


class AIDatabase:
  """AI database."""

  def __init__(
    self,
    config: app_config.AppConfig,
    *,
    read_only: bool = False,
    aes_key: aes.AESKey | None = None,
    safe_save: bool = True,
    compress_save: bool = False,
  ) -> None:
    """Initialize the AI Database.

    Args:
      config: The application configuration object.
      read_only: (default False) Whether to open the database in read-only mode.
      aes_key: (default None) Optional AES key for encrypting/decrypting the database file
      safe_save: (default True) Whether to use a safe save method that reads the existing DB file
          before writing, to prevent data loss from clobbering; if False, it will overwrite
          the file directly
      compress_save: (default False) Whether to compress the DB file when saving; if True, it will
          save as a compressed file

    """
    self._config: app_config.AppConfig = config
    self._read_only: bool = read_only
    self._key: aes.AESKey | None = aes_key
    self._safe_save: bool = safe_save
    self._compress_save: bool = compress_save
    self._db: _DBType
    self._open = timer.Timer('AIDatabase', emit_log=False)
    with _DB_DISK_LOCK:  # ensure thread-safe load operations
      if self._config.path.exists():
        self._db = cast(
          '_DBType', config.DeSerialize(decryption_key=self._key, unpickler=key.UnpickleJSON)
        )
        logging.info(f'Loaded DB from {self._config.path}: {self.label}')
      else:
        self._db = _DBTypeFactory()
        logging.warning(f'DB file not found, will start fresh, {self.label}')
    if self._read_only:
      logging.warning('ATTENTION: AIDatabase opened in read-only mode, changes will not be saved!')

  def __enter__(self) -> Self:
    """Context manager entry, returns self.

    Returns:
      self, for use within the context

    """
    return self

  def __exit__(
    self,
    exc_type: type[BaseException] | None,
    _exc_value: BaseException | None,
    _traceback: object,
  ) -> None:
    """Context manager exit. If not exception, saves the database to file.

    Args:
      exc_type: exception type, if any
      _exc_value: exception value, if any
      _traceback: traceback object, if any

    """
    logging.info(f'AIDatabase was open for {self._open}')
    if exc_type is not None:
      logging.error('Exception occurred in AIDatabase context: *NOT* saving DB due to exception')
      return  # do not save if there was an exception
    self.Save()

  @property
  def label(self) -> str:
    """Get a human-readable label for the database, for logging and display purposes.

    Returns:
      string '#<N>@<tm>'

    """
    return _DBLabel(self._db)

  @property
  def output(self) -> pathlib.Path | None:
    """Get current output directory for generated images.

    Returns:
      pathlib.Path or None if not set

    """
    return pathlib.Path(self._db['image_output_dir']) if self._db['image_output_dir'] else None

  @output.setter
  def output(self, value: pathlib.Path | str | None) -> None:
    """Set current output directory for generated images.

    Args:
      value: pathlib.Path, string path, or None to clear the output directory

    Raises:
      Error: if the provided path is invalid (does not exist or is not a directory)

    """
    path: pathlib.Path | None = (
      pathlib.Path(value).expanduser().resolve() if value is not None else None
    )
    if path is None:
      self._db['image_output_dir'] = None
      logging.info('Cleared DB image output directory')
      return
    if not path.exists() or not path.is_dir():
      raise Error(f'Invalid output directory: {path} (must exist and be a directory)')
    str_path: str = str(path)
    self._db['image_output_dir'] = str_path
    if str_path not in self._db['known_image_sources']:
      self._db['known_image_sources'].append(str_path)  # track this path as a known image source
    logging.info(f'Set DB image output directory to: {path} (also added to known image sources)')

  def Save(self) -> None:
    """Save the database to file.

    Raises:
      Error: if safe_save is enabled and the existing DB on disk differs from the loaded DB

    """
    if self._read_only:
      logging.warning('AIDatabase in read-only mode: will *NOT* save! (would have saved now)')
      return
    with _DB_DISK_LOCK:  # ensure thread-safe save operations
      # check on previous save
      if self._safe_save and self._config.path.exists():
        logging.debug('Safe save enabled, reading existing DB before saving to prevent data loss')
        existing_db: _DBType = cast(
          '_DBType',
          self._config.DeSerialize(
            decryption_key=self._key, unpickler=key.UnpickleJSON, silent=True
          ),
        )
        if (
          existing_db['version'] != self._db['version']
          or existing_db['last_save'] != self._db['last_save']
        ):
          raise Error(
            f'DB on disk {_DBLabel(existing_db)} differs from loaded DB {self.label}, '
            'aborting save to prevent data loss'
          )
      # update DB metadata before saving
      prev_label: str = self.label
      self._db.update(
        {
          'version': self._db['version'] + 1,  # increment DB version on each save
          'db_version': __version__,  # set to current package version on creation
          'last_save': timer.Now(),
        }
      )
      # save the DB to disk with optional encryption and compression
      self._config.Serialize(
        cast('tbase.JSONDict', self._db),
        encryption_key=self._key,
        pickler=key.PickleJSON,
        compress=_DB_COMPRESS_LEVEL if self._compress_save else None,
      )
      logging.info(f'DB saved to {self._config.path}: {prev_label} -> {self.label}')

  def RefreshDBModels(self, api: APIProtocol) -> None:
    """Refresh the DB models by fetching from the API and updating the DB. Does NOT delete models.

    Args:
      api: APIProtocol instance to use for fetching available models

    """
    models: list[AIModelType] = api.GetModels()
    # add missing hashes
    all_paths: set[str] = {model['path'] for model in self._db['models'].values() if model['path']}
    for model in models:
      if model['path'] in all_paths:
        continue  # skip duplicates by path (we know we have this one), we only want unique models
      if not model['hash'].strip():
        logging.warning(f'Model with empty hash received from API, hashing {model["path"]}')
        model['hash'] = hashes.Hash256(pathlib.Path(model['path']).read_bytes()).hex()
      logging.info(f'Adding model to DB: {model["name"]} -> {model["hash"]}')
      self._db['models'][model['hash']] = model  # add to DB models
    # done, log
    logging.info(f'Refreshed DB models; total models in DB: {len(self._db["models"])}')

  def GetModelHash(self, model_name: str, *, api: APIProtocol | None = None) -> str:
    """Get the model hash for a given model key. If API is given will also try to fetch.

    Args:
      model_name: The model name to look up
      api: (default None) APIProtocol instance to use for fetching available models automatically;
          if None, it will only search in the existing DB models and will not attempt to fetch

    Returns:
      The model hash corresponding to the given model name

    Raises:
      Error: on error or if the model is not found

    """
    # check the name
    model_name = model_name.lower().strip()
    if not model_name:
      raise Error('Model name cannot be empty')
    # search in DB models
    possible_models: list[AIModelType] = [
      model for model in self._db['models'].values() if model_name in model['name'].lower()
    ]
    if len(possible_models) > 1:
      raise Error(f'Multiple models found matching name "{model_name}": {possible_models}')
    if len(possible_models) == 1:
      return possible_models[0]['hash']  # found unique
    # model not found, we will fetch *all* models, if possible
    if not api:
      raise Error(f'Model with name "{model_name}" not found in DB')  # in this case it's an error!
    logging.warning(f'Model with name "{model_name}" not found in DB, fetching all models from API')
    self.RefreshDBModels(api)
    # we have refreshed the DB models, try searching again
    possible_models = [
      model for model in self._db['models'].values() if model_name in model['name'].lower()
    ]
    if len(possible_models) > 1:
      raise Error(f'Multiple models found matching name "{model_name}": {possible_models}')
    if len(possible_models) == 1:
      return possible_models[0]['hash']  # found unique
    raise Error(
      f'Model with name "{model_name}" not found, try available names: '
      f'{[model["name"] for model in self._db["models"].values()]}'
    )

  def Txt2Img(self, meta: AIMetaType, api: APIProtocol) -> tuple[DBImageType, bytes]:
    """Generate image from text prompt, store in DB.

    Args:
      meta: AIMetaType object containing the generation metadata (e.g., prompt, steps,
          seed, width, height, sampler_id, model_key)
      api: APIProtocol instance to use for making the API call

    Returns:
      A tuple containing the DBImageType object and the raw image data.

    Raises:
      Error: on error

    """
    # we have the model?
    if meta['model_hash'] not in self._db['models']:
      raise Error(f'Model with hash {meta["model_hash"]} not found in DB models')
    # try to find it here already
    db_entry: DBImageType
    for h, db_entry in self._db['images'].items():
      if db_entry['path'] and db_entry['ai_meta'] == meta:
        # we have a file that matches, or should have...
        path = pathlib.Path(db_entry['path'])
        if not path.exists():
          logging.warning(f'Image {meta} should exist as {h}: {path} but FILE NOT FOUND')
          db_entry['path'] = None  # clear the path since it's not valid
          continue  # give up on this, probably means this entry will be replaced...
        logging.info(f'Image {meta} exists with hash {h}: {path}')
        return (db_entry, path.read_bytes())
    # not found, generate new
    img_bytes: bytes
    db_entry, img_bytes = api.Txt2Img(
      self._db['models'][meta['model_hash']].copy(), meta, dir_root=self.output
    )
    self._db['images'][db_entry['hash']] = db_entry.copy()  # add to DB images
    return (db_entry, img_bytes)

  def Sync(  # noqa: C901, PLR0912, PLR0914, PLR0915
    self, *, add_dir: pathlib.Path | str | None = None, api: APIProtocol | None = None
  ) -> None:
    """Go over all known image dirs, check for new/deleted images, update DB accordingly.

    Args:
      add_dir: (default None) Optional additional dir to add to known image sources and sync with
      api: (default None) APIProtocol instance to use for fetching available models automatically;
          if None, it will only search in the existing DB models and will not attempt to fetch

    Raises:
      Error: if the provided path is invalid or other errors

    """
    add_dir = pathlib.Path(add_dir).expanduser().resolve() if add_dir else None
    if add_dir and (not add_dir.exists() or not add_dir.is_dir()):
      raise Error(f'Provided directory for sync does not exist: {add_dir}')
    # if API is provided, we will refresh the DB models first
    if api:
      logging.info('API provided for sync, refreshing DB models first')
      self.RefreshDBModels(api)
    # add the new dir to known sources if not already present
    if add_dir:
      str_add_dir: str = str(add_dir)
      if str_add_dir not in self._db['known_image_sources']:
        self._db['known_image_sources'].append(str_add_dir)
        logging.info(f'Added new image source dir: {add_dir}')
    # scan all known source dirs for image files
    is_target: abc.Callable[[pathlib.Path], bool] = lambda p: (
      p.suffix.lower() in _EXTENSIONS_TO_PARSE_LOWER and p.is_file()
    )
    files_todo: list[pathlib.Path] = []
    valid_sources: int = 0
    invalid_sources: int = 0
    for dir_path in sorted(pathlib.Path(d) for d in self._db['known_image_sources']):  # determinism
      # check the source dir exists and is a directory
      if not dir_path.exists() or not dir_path.is_dir():
        logging.error(f'Known image source dir does not exist, skipping: {dir_path}')
        invalid_sources += 1
        continue
      # we have a valid source dir, scan for images
      filtered_dir: list[pathlib.Path] = [p for p in sorted(dir_path.rglob('*')) if is_target(p)]
      files_todo.extend(filtered_dir)  # add the sorted (for determinism) list of files to the todo
      valid_sources += 1
      logging.info(f'Valid source dir with {len(filtered_dir)} images added: {dir_path}')
    logging.info(
      f'Found {len(files_todo)} total image files to sync from {valid_sources} valid dir sources '
      f'(skipped {invalid_sources} invalid sources)'
    )
    # now go over them with a progress bar, confident they are valid, and update the DB accordingly
    valid_image: int = 0
    invalid_image: int = 0
    new_image: int = 0
    meta_error: int = 0
    img_error: int = 0
    Image.MAX_IMAGE_PIXELS = 500_000_000  # set a high limit to avoid DecompressionBombError
    with timer.Timer(emit_log=False) as tmr_add:
      for img_path in tqdm.tqdm(
        iterable=files_todo,
        total=len(files_todo),  # strictly not necessary, but helps if need to enumerate() for debug
        desc='Read',
        unit='img',
        dynamic_ncols=True,
        smoothing=0.001,
        colour='green',
      ):
        # try to read the file and hash it
        try:
          img_bytes: bytes = img_path.read_bytes()
        except OSError:
          logging.error(f'Cannot read image file, skipping: {img_path}')
          invalid_image += 1
          continue
        img_hash: str = hashes.Hash256(img_bytes).hex()
        valid_image += 1
        # do we know this hash?
        if img_hash in self._db['images']:
          # already known — update path tracking if needed
          db_entry: DBImageType = self._db['images'][img_hash]
          str_path: str = str(img_path)
          alt_path: set[str] = set(db_entry['alt_path'])
          if db_entry['path'] is None:
            # add to main entry, remove from alt if it was there
            db_entry['path'] = str_path
            logging.debug(f'Restored path for known image {img_hash[:12]}: {img_path}')
            db_entry['alt_path'] = sorted(alt_path - {str_path})
          elif db_entry['path'] != str_path:
            # main entry has a different path, add this one to alt paths if not already there
            db_entry['alt_path'] = sorted(alt_path | {str_path})
            logging.debug(f'Added alt path for image {img_hash[:12]}: {img_path}')
        else:
          # new image — parse metadata and add to DB
          try:
            new_entry: DBImageType = _ImportImageFile(
              img_path, img_bytes, img_hash, set(self._db['models'])
            )
            self._db['images'][img_hash] = new_entry
            new_image += 1
            if new_entry['parse_errors']:
              meta_error += 1
            logging.debug(f'Imported new image {img_hash[:12]}: {img_path}')
          except (ValueError, tbase.Error) as err:
            img_error += 1
            logging.error(f'Could not import image, skipping {img_path}: {err}')
    # done, log
    logging.info(
      f'Sync done in {tmr_add}: {len(self._db["images"])} unique hashes in DB. '
      f'Scanned {valid_sources} dir sources containing {valid_image} valid images and '
      f'{invalid_image} invalid images; of these, {new_image} were new and added to the DB, '
      f'{meta_error} had metadata errors, {img_error} had irrecoverable errors and were ignored. '
      'Now checking for deleted images...'
    )
    # check for deleted images — paths that no longer exist on disk
    total_paths: int = 0
    existing_paths: int = 0
    with timer.Timer(emit_log=False) as tmr_del:
      for img_hash, db_entry in tqdm.tqdm(
        iterable=self._db['images'].items(),
        desc='Check',
        unit='img',
        dynamic_ncols=True,
        smoothing=0.001,
        colour='red',
      ):
        # gather all known paths for this image (main + alt), check which ones still exist
        all_paths: set[str] = set(db_entry['alt_path'])
        if db_entry['path']:
          all_paths.add(db_entry['path'])
        total_paths += len(all_paths)
        filtered_paths: set[str] = {p for p in all_paths if pathlib.Path(p).exists()}
        existing_paths += len(filtered_paths)
        # if none of the paths exist, clear the path info but keep the DB entry
        if not filtered_paths:
          logging.warning(f'All paths for image {img_hash[:12]} are gone, clearing: {all_paths}')
          db_entry['path'] = None
          db_entry['alt_path'] = []
          continue
        # we have at least one existing path, if the main path is gone, promote an alt path to main
        if not db_entry['path'] or (
          db_entry['path'] and not pathlib.Path(db_entry['path']).exists()
        ):
          db_entry['path'] = filtered_paths.pop()  # promote one of the existing paths to main
          db_entry['alt_path'] = sorted(filtered_paths)  # the rest become alt paths
        else:
          # we should have an OK db_entry['path'] that exists, we remove it from the rest
          filtered_paths.discard(db_entry['path'])
          db_entry['alt_path'] = sorted(filtered_paths)
    # done, log
    logging.info(
      f'Check done in {tmr_del}: {len(self._db["images"])} unique hashes in DB. '
      f'In the DB we had {total_paths} total paths, {existing_paths} still existing, '
      f'so we dropped {total_paths - existing_paths} paths.'
    )


_PARAMS_LINE_RE: re.Pattern[str] = re.compile(
  r'^(Steps|Sampler|CFG scale|Seed|Size|Model)\s*:', re.IGNORECASE
)
_PARAM_SPLIT_RE: re.Pattern[str] = re.compile(r',\s*(?=[A-Za-z][A-Za-z0-9 _]*:)', re.IGNORECASE)


def _ParseImageMetadata(info_text: str) -> dict[str, str]:  # noqa: C901, PLR0912, PLR0914
  """Parse SDNext/A1111 image metadata string into a key-value dict.

  The metadata string has the structure::

    positive prompt text
    Negative prompt: negative prompt text
    Steps: 10, Size: 256x256, Sampler: DPM++ SDE, ..., Seed: 666, Model hash: abc123, ...

  Args:
    info_text: The raw metadata string from PIL ``img.info``.

  Returns:
    A dict with lowercase keys including ``'positive'``, ``'negative'`` (may be ``None``/absent),
    plus all the comma-separated key-value pairs in lowercase with stripped values.
    Size is split into ``'width'`` and ``'height'``.

  """
  lines: list[str] = info_text.strip().split('\n')
  result: dict[str, str] = {}
  # gather positive prompt lines until we hit the negative or params line
  positive_lines: list[str] = []
  remainder: str = ''
  for i, line in enumerate(lines):
    if line.startswith('Negative prompt:'):
      # everything from here on is remainder to parse; preserve newlines for later splitting
      remainder = '\n'.join([line, *lines[i + 1 :]])
      break
    # check if this line looks like a params line (starts with a known keyword + colon + number)
    if _PARAMS_LINE_RE.match(line):
      remainder = ' '.join(lines[i:])
      break
    positive_lines.append(line)
  else:
    # no break — all lines are prompt
    remainder = ''
  result['positive'] = '\n'.join(positive_lines).strip()
  # split remainder into negative prompt and params
  if remainder.startswith('Negative prompt:'):
    # do NOT strip before splitting — we need '\n' separators preserved (e.g. empty negative)
    neg_and_params: str = remainder[len('Negative prompt:') :]
    # the negative prompt may span multiple lines; consume lines until we hit a params line,
    # mirroring the same logic used for the positive prompt above
    neg_lines: list[str] = neg_and_params.split('\n')
    negative_parts: list[str] = []
    params_start: int = len(neg_lines)  # default: all lines belong to negative
    for j, neg_line in enumerate(neg_lines):
      if _PARAMS_LINE_RE.match(neg_line):
        params_start = j
        break
      negative_parts.append(neg_line)
    result['negative'] = '\n'.join(negative_parts).strip()
    remainder = ' '.join(neg_lines[params_start:]) if params_start < len(neg_lines) else ''
  # parse comma-separated key: value pairs from remainder
  # we can't just split on ',' because values may contain commas (model names, etc.)
  # instead we split on ', <Key>:' boundaries using regex
  param_text: str = remainder.strip()
  if param_text:
    # split on boundaries where ', Word:' or ', Word Word:' appear
    parts: list[str] = _PARAM_SPLIT_RE.split(param_text)
    for part in parts:
      if ':' not in part:
        continue
      k, _, v = part.partition(':')
      key_norm: str = k.strip().lower()
      val_norm: str = v.strip()
      if key_norm == 'size':
        # split 'WxH' or 'W x H' into separate keys
        size_match: re.Match[str] | None = re.match(r'(\d+)\s*[xX]\s*(\d+)', val_norm)
        if size_match:
          result['width'] = size_match.group(1)
          result['height'] = size_match.group(2)
      else:
        result[key_norm] = val_norm
  # done
  return result


def _FindModelHash(partial_hash: str, models: set[str]) -> str:
  """Find a full model hash in the DB by prefix-matching a partial hash.

  Args:
    partial_hash: A partial (prefix) hash string to match against DB model hashes.
    models: The DB models set (hashes only).

  Returns:
    The full model hash if a unique prefix match is found, or an empty string if not found

  Raises:
    Error: on error

  """
  partial_hash = partial_hash.strip().lower()
  if not partial_hash:
    raise Error('empty model hash')
  if partial_hash in models:
    return partial_hash  # exact match
  matches: list[str] = [h for h in models if h.lower().startswith(partial_hash)]
  if len(matches) == 1:
    logging.debug(f'Matched partial model hash {partial_hash!r} -> {matches[0]}')
    return matches[0]  # found!
  if len(matches) > 1:
    raise Error(f'ambiguous model #{partial_hash} matches {len(matches)}')
  raise Error(f'model #{partial_hash} not found')


def _ImportImageFile(  # noqa: C901, PLR0912, PLR0914, PLR0915
  img_path: pathlib.Path, img_bytes: bytes, img_hash: str, models: set[str]
) -> DBImageType:
  """Parse an image file from disk and create a DBImageType entry.

  Supports SDNext/A1111 PNG metadata in ``img.info['parameters']`` or
  ``img.info['UserComment']``.

  Args:
    img_path: Path to the image file.
    img_bytes: Raw bytes of the image file (already read).
    img_hash: Precomputed SHA-256 hex digest of the file bytes.
    models: The DB models set (hashes only).

  Returns:
    A populated DBImageType for the image.

  Raises:
    Error: unsupported format or AI incomplete image

  """
  # open image from buffer
  with Image.open(io.BytesIO(img_bytes)) as img:
    # make sure format is known
    fmt: ImageFormat | None = _PIL_FORMAT_MAP.get((img.format or '').upper())
    if not fmt:
      raise Error(f'Unsupported image format {img.format!r}')
    # get the internal data we need (size and hash)
    width: int = img.width
    height: int = img.height
    raw_hash: str = hashes.Hash256(img.convert('RGBA').tobytes()).hex()
    # try to extract metadata from PNG info tags, either 'parameters' or 'UserComment'
    info_text: str = ''
    pil_info: tbase.JSONDict = img.info  # type: ignore[assignment]
    if 'parameters' in pil_info and isinstance(pil_info['parameters'], str):
      info_text = pil_info['parameters']
    elif 'UserComment' in pil_info and isinstance(pil_info['UserComment'], str):
      info_text = pil_info['UserComment']
  # we have the metadata text, first check it is an AI image
  if not info_text.strip():
    # could not find metadata, we consider this a non-AI image
    return DBImageType(
      hash=img_hash,
      raw_hash=raw_hash,
      path=str(img_path),
      alt_path=[],
      size=len(img_bytes),
      width=width,
      height=height,
      format=fmt.value,
      created_at=int(img_path.stat().st_mtime),
      origin=None,
      version=None,
      ai_meta=None,
      sd_info={},
      sd_params={},
      parse_errors=['no AI metadata'],
    )
  # parse metadata
  # TODO: create a field and make sure to distinguish txt2img vs img2img
  # TODO: lora metadata
  meta_raw: dict[str, str] = _ParseImageMetadata(info_text) if info_text else {}
  parse_errors: list[str] = []
  # resolve model hash
  partial: str = meta_raw.get('model hash', '')
  model_hash: str | None = None
  try:
    model_hash = _FindModelHash(partial, models) if partial else None
  except Error as err:
    parse_errors.append(str(err))
  # get version
  img_origin: ImageOrigin | None = None
  app_version: str | None = None
  empty_query_parser: str = base.SD_EMPTY_QUERY_PARSER
  if meta_raw.get('version'):
    if meta_raw.get('app', '').lower() == 'sd.next':
      # if loading through here, SDNext undistinguishable from TransNext
      img_origin, app_version = ImageOrigin.SDNext, meta_raw['version']
      empty_query_parser = base.QueryParser.SDNextNative.value
    else:
      img_origin, app_version = ImageOrigin.A1111, meta_raw['version']
      empty_query_parser = base.QueryParser.A1111.value
  # build metadata for DB entry, using defaults if parsing fails or fields are missing

  def _IntKey(key: str, default: int, *, empty: str | None = None) -> int:
    try:
      return int(meta_raw.get(key, empty or ('no ' + key)))
    except ValueError as err:
      parse_errors.append(f'{key}: {err} -> {default}')
      return default

  def _FloatKey(key: str, default: int, *, empty: str | None = None, conversion: int = 10) -> int:
    try:
      return round(float(meta_raw.get(key, empty or ('no ' + key))) * conversion)
    except ValueError as err:
      parse_errors.append(f'{key}: {err} -> {default}')
      return default

  def _EnumKey[T: enum.Enum](tp: type[T], key: str, default: T, *, empty: str | None = None) -> T:
    try:
      return tp(meta_raw.get(key, empty or ('no ' + key)))
    except ValueError as err:
      parse_errors.append(f'{key}: {err} -> {default.value}')
      return default

  v_seed: int = _IntKey('variation seed', -1, empty=base.SD_EMPTY_V_SEED)
  v_strength: int = _FloatKey(
    'variation strength', 0, empty=base.SD_EMPTY_V_STRENGTH, conversion=100
  )
  ai_meta: AIMetaType = AIMetaType(
    # MANDATORY FIELDS (must be present and valid, otherwise we consider this image as malformed)
    model_hash=model_hash,
    positive=meta_raw.get('positive', ''),
    seed=_IntKey('seed', -1),
    v_seed=(v_seed, v_strength) if v_seed > 0 and 0 < v_strength <= 100 else None,  # noqa: PLR2004
    width=width,
    height=height,
    steps=_IntKey('steps', 0),
    cfg_scale=_FloatKey('cfg scale', 0),
    sampler=_EnumKey(base.Sampler, 'sampler', base.Sampler.Euler_A).value,
    # OPTIONAL FIELDS (if missing will have defaults, but if present must be valid)
    negative=meta_raw.get('negative') or None,
    cfg_end=_FloatKey('cfg end', 0, empty=base.SD_EMPTY_CFG_END),
    parser=_EnumKey(
      base.QueryParser, 'parser', base.SD_DEFAULT_QUERY_PARSER, empty=empty_query_parser
    ).value,
    clip_skip=_FloatKey('clip skip', 0, empty=base.SD_EMPTY_CLIP_SKIP),
  )
  # do checks; be strict
  # SEED
  if not 0 < ai_meta['seed'] <= base.SD_MAX_SEED:
    parse_errors.append('`seed` out of bounds')
  # DIMENSIONS
  meta_width = int(meta_raw.get('width', 'no width'))
  meta_height = int(meta_raw.get('height', 'no height'))
  if meta_width != width or meta_height != height:
    meta_px: int = meta_width * meta_height
    actual_px: int = width * height
    if meta_px and actual_px and meta_px < actual_px and actual_px / meta_px > 1.5:  # noqa: PLR2004
      # the hallmark of a img->img upscaler: actual >> meta, and a significant difference
      parse_errors.append('upscaled')
    elif (
      meta_width  # noqa: PLR0916
      and meta_height
      and (meta_width % 16 or meta_height % 16)
      and not width % 16
      and not height % 16
      and actual_px
      and meta_px > actual_px
      and meta_px / actual_px < 1.1  # noqa: PLR2004
    ):
      # the hallmark of an image that had its dimensions corrected to be a multiple of 16:
      # meta is not a multiple, but actual is, and they are super close in dimensions
      parse_errors.append('size corrected / 16')
    elif (
      meta_width  # noqa: PLR0916
      and meta_height
      and (meta_width % 8 or meta_height % 8)
      and not width % 8
      and not height % 8
      and actual_px
      and meta_px > actual_px
      and meta_px / actual_px < 1.1  # noqa: PLR2004
    ):
      # the hallmark of an image that had its dimensions corrected to be a multiple of 8:
      # meta is not a multiple, but actual is, and they are super close in dimensions
      parse_errors.append('size corrected / 8')
    else:
      extra_msg: str = '; probably an unfinished image' if meta_px > actual_px else ''
      raise Error(f'Dim error: {meta_width} x {meta_height} / {width} x {height}{extra_msg}')
  # STEPS, CFG SCALE, CFG END, CLIP SKIP
  if not 1 <= ai_meta['steps'] <= base.SD_MAX_ITERATIONS:
    parse_errors.append('`steps` out of bounds')
  if not 10 <= ai_meta['cfg_scale'] <= base.SD_MAX_CFG_SCALE:  # noqa: PLR2004
    parse_errors.append('`cfg_scale` out of bounds')
  if not 0 <= ai_meta['cfg_end'] <= 10:  # noqa: PLR2004
    parse_errors.append('`cfg_end` out of bounds')
  if not 10 <= ai_meta['clip_skip'] <= base.SD_MAX_CLIP_SKIP:  # noqa: PLR2004
    parse_errors.append('`clip_skip` out of bounds')
  # join everything together into the DBImageType
  if parse_errors:
    logging.debug(f'Parsed image metadata with errors: {info_text}, errors: {parse_errors}')
  return DBImageType(
    hash=img_hash,
    raw_hash=raw_hash,
    path=str(img_path),
    alt_path=[],
    size=len(img_bytes),
    width=width,
    height=height,
    format=fmt.value,
    created_at=int(img_path.stat().st_mtime),
    origin=img_origin.value if img_origin else ImageOrigin.AIUnknown.value,  # we could parse!
    version=app_version,
    ai_meta=ai_meta,
    sd_info={},
    sd_params=meta_raw,  # type: ignore[typeddict-item]
    parse_errors=parse_errors,
  )


def _DBLabel(db: _DBType) -> str:
  """Get a human-readable label for the database, for logging and display purposes.

  Returns:
    string '#<N>@<tm>'

  """
  return f'#{db["version"]}@{timer.TimeStr(db["last_save"])}'


@runtime_checkable
class APIProtocol(Protocol):
  """SDNext API protocol contract needed by the DB."""

  @abstract.abstractmethod
  def GetModels(self) -> list[AIModelType]:
    """Get list of available models from SDNext API.

    Returns:
      A list of AIModelType objects representing the available models. BEWARE: hash may be ''!

    Raises:
      Error: If there is an error with the API call or if the response is invalid.

    """

  @abstract.abstractmethod
  def Txt2Img(
    self, model: AIModelType, meta: AIMetaType, *, dir_root: pathlib.Path | None = None
  ) -> tuple[DBImageType, bytes]:
    """Generate image from text prompt using SDNext API.

    See: <https://github.com/vladmandic/sdnext/blob/master/cli/api-txt2img.py>

    Args:
      model: AIModelType object representing the model to use for generation
      meta: AIMetaType object containing the generation metadata (e.g., prompt, steps,
          seed, width, height, sampler_id, model_key)
      dir_root: (default: None) Directory root to save the generated image, if None don't save

    Returns:
      A tuple containing the DBImageType object and the raw image data.

    Raises:
      Error: If there is an error with the API call, if the response is invalid,
          or if the image data is invalid.

    """
